# Generated by Django 4.0.6 on 2022-07-11 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_API', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
