# Generated by Django 4.0.6 on 2022-07-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_API', '0002_alter_component_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specifications',
            unique_together={('product', 'component')},
        ),
    ]
