# Generated by Django 4.0.6 on 2022-07-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_API', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
