# Generated by Django 4.0.6 on 2022-07-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_API', '0005_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'product')},
        ),
    ]
