# Generated by Django 4.0.6 on 2022-07-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_API', '0006_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
