# Generated by Django 4.0.6 on 2022-07-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_API', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
    ]
