# Generated by Django 4.0.6 on 2022-07-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_API', '0008_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(null=True, upload_to='avatars/'),
        ),
    ]
