# Generated by Django 4.0.6 on 2022-07-21 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_API', '0010_componenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_store_API.componenttype')),
            ],
        ),
    ]
