# Generated by Django 4.0.6 on 2022-07-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_API', '0012_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.FileField(default=None, upload_to='categories/'),
        ),
    ]
