# Generated by Django 4.0.6 on 2022-07-21 16:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_API', '0014_alter_productcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_store_API.component')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_store_API.product')),
            ],
        ),
    ]
